language: cpp
sudo: required
dist: bionic
os: linux

before_install:
  - ./install_catch2.sh

install:
  # Install Paho MQTT C (Need only paho-mqtt3a and paho-mqtt3as)
  - ./install_paho_mqtt_c.sh

addons:
  apt:
    sources:
      - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
      - cppcheck
      - libcppunit-dev
      - git
      - cmake
      - cmake-data
      - doxygen
      - mosquitto

matrix:
  include:
    # GCC 5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
          packages:
            - g++-5
            - cppcheck
            - libcppunit-dev
            - git
            - cmake
            - cmake-data
            - doxygen
            - mosquitto
      env: COMPILER=g++-5
    # GCC 6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
          packages:
            - g++-6
            - cppcheck
            - libcppunit-dev
            - git
            - cmake
            - cmake-data
            - doxygen
            - mosquitto
      env: COMPILER=g++-6
    # GCC 7
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
          packages:
            - g++-7
            - cppcheck
            - libcppunit-dev
            - git
            - cmake
            - cmake-data
            - doxygen
            - mosquitto
      env: COMPILER=g++-7
    # GCC 8
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
          packages:
            - g++-8
            - cppcheck
            - libcppunit-dev
            - git
            - cmake
            - cmake-data
            - doxygen
            - mosquitto
      env: COMPILER=g++-8
    # Clang 3.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
          packages:
            - clang-3.9
            - cppcheck
            - libcppunit-dev
            - git
            - cmake
            - cmake-data
            - doxygen
            - mosquitto
      env: COMPILER=clang++-3.9
    # Clang 4.0
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
          packages:
            - clang-4.0
            - cppcheck
            - libcppunit-dev
            - git
            - cmake
            - cmake-data
            - doxygen
            - mosquitto
      env: COMPILER=clang++-4.0
  exclude:
    - compiler: gcc

script:
  # Test build
  - ./travis_build.sh
  # Static Analysis
  - cppcheck --enable=all --std=c++11 --force --quiet src/*.cpp

